# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainform(object):
    def setupUi(self, Mainform):
        Mainform.setObjectName("Mainform")
        Mainform.setEnabled(True)
        Mainform.resize(1286, 654)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mainform.sizePolicy().hasHeightForWidth())
        Mainform.setSizePolicy(sizePolicy)
        Mainform.setMinimumSize(QtCore.QSize(1, 0))
        Mainform.setAutoFillBackground(True)
        Mainform.setStyleSheet("")
        self.Title = QtWidgets.QLabel(Mainform)
        self.Title.setGeometry(QtCore.QRect(450, 20, 441, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title.setAutoFillBackground(False)
        self.Title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Title.setObjectName("Title")
        self.printWindow = QtWidgets.QTextEdit(Mainform)
        self.printWindow.setGeometry(QtCore.QRect(20, 370, 1251, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.printWindow.setFont(font)
        self.printWindow.setToolTip("")
        self.printWindow.setObjectName("printWindow")
        self.start = QtWidgets.QPushButton(Mainform)
        self.start.setGeometry(QtCore.QRect(1020, 90, 251, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/picture/Elephant.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon)
        self.start.setIconSize(QtCore.QSize(64, 64))
        self.start.setObjectName("start")
        self.banquan = QtWidgets.QLabel(Mainform)
        self.banquan.setGeometry(QtCore.QRect(460, 610, 351, 26))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.banquan.setFont(font)
        self.banquan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.banquan.setObjectName("banquan")
        self.groupBox = QtWidgets.QGroupBox(Mainform)
        self.groupBox.setGeometry(QtCore.QRect(0, 170, 1281, 191))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(20, 30, 600, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_2.setEnabled(True)
        self.listWidget_2.setGeometry(QtCore.QRect(670, 30, 600, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setObjectName("listWidget_2")
        self.comboBox = QtWidgets.QComboBox(Mainform)
        self.comboBox.setGeometry(QtCore.QRect(20, 90, 881, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Mainform)
        QtCore.QMetaObject.connectSlotsByName(Mainform)

    def retranslateUi(self, Mainform):
        _translate = QtCore.QCoreApplication.translate
        Mainform.setWindowTitle(_translate("Mainform", "Dialog"))
        self.Title.setText(_translate("Mainform", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'仿宋\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Python调用CANoe测试工具软件</p></body></html>"))
        self.start.setText(_translate("Mainform", "Start"))
        self.banquan.setText(_translate("Mainform", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'仿宋\'; font-size:18pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#000000;\">©</span><span style=\" font-size:12pt; font-style:italic; color:#000000;\">CSDN</span><span style=\" font-size:12pt; font-weight:400; font-style:italic; color:#000000;\">蚂蚁小兵</span></p></body></html>"))

